### ISSUE TITLE
Is this work around still necessary or has ASUS updated the BIOS to address this issue?

### ISSUE THREAD

**Issue by ioogithub** [badgers-ua/asus_zenbook_ux5304va_sound#2]
The initial post says "as of now" and that was 5 months ago. I see there has been a few BIOS updates since then.

In this thread, a user reports updating the BIOS to get sound working:
https://askubuntu.com/questions/1442499/ubuntu-22-04-on-asus-zenbook-s-13-oled
so that might suggest that it has been fixed. 

This link would suggest that it is not working:
https://wiki.archlinux.org/title/Laptop/ASUS

I can't tell from these discussion of it is working or not:
https://bugzilla.kernel.org/show_bug.cgi?id=216194#c29
https://github.com/thesofproject/linux/issues/3814
https://superuser.com/questions/1719920/no-sound-from-internal-speakers-on-laptop-but-headphone-jack-and-hdmi-works

A user tried a patch and it did not work:
https://www.reddit.com/r/linuxhardware/comments/165hl0x/no_sound_on_asus_zenbook_s_13_oled_ux5304/

Can you confirm, has this been fixed with a BIOS update or is this work around still necessary?

**Comment by crankshift** [comment]
Can't confirm or deny this, unfortunately, since after few days after the purchase I returned my laptop.
