### ISSUE TITLE
The latest linux kernel (6.7.3) has the UX5304VA solution inside

### ISSUE THREAD

**Issue by DolevRavid** [badgers-ua/asus_zenbook_ux5304va_sound#3]
I spent a lot of hours in order to compile my kernel,
when I finally fined a guide for it I downloaded the last version and found that inside the patch_realtek.c file there's a build-in line that already including the UX5304VA. 
so instead of compiling and installing I just download the "mainline kernels" and installed the kernel from there. 
after reboot i realized that everything working pretty well :)

**Comment by crankshift** [comment]
thanks for the update, I don't own a laptop anymore so I'm not maintaining this solution, but will update the guide

**Comment by matanox** [comment]
@DolevRavid Could you maybe extend some advice for a different Zenbook model, Zenbook UX3402ZA, along with a more elaborate description of what needs to be done? Is the procedure fully reversible?

What linux distro were you using on top of the kernel in your case?

**Comment by DolevRavid** [comment]
I actually don't know what's the situation in other models.
But I'm using Fedora and it seems like the widest support distro - you
should check it out :)

‫בתאריך יום ג׳, 9 באפר׳ 2024 ב-14:36 מאת ‪Matan Addam‬‏ <‪
***@***.***‬‏>:‬
